"""Add sets, reps, weight to UserWorkout

Revision ID: 18f2e6bb0c50
Revises: ad8262870859
Create Date: 2024-11-26 19:47:59.241235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18f2e6bb0c50'
down_revision = 'ad8262870859'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_workout', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sets', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('reps', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('weight', sa.Float(), nullable=True))
        batch_op.alter_column('workout_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_workout', schema=None) as batch_op:
        batch_op.alter_column('workout_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('weight')
        batch_op.drop_column('reps')
        batch_op.drop_column('sets')

    # ### end Alembic commands ###
