"""workout table no longer require unique userids

Revision ID: 7ace4d590116
Revises: e8ca04662bb1
Create Date: 2024-11-30 18:10:40.924208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ace4d590116'
down_revision = 'e8ca04662bb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_exercies')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_exercies',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('workout_id', sa.INTEGER(), nullable=False),
    sa.Column('set_number', sa.INTEGER(), nullable=False),
    sa.Column('weight', sa.INTEGER(), nullable=False),
    sa.Column('reps', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['workout_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id', 'set_number', 'weight', 'reps')
    )
    # ### end Alembic commands ###
