"""Add completed field to UserGoal

Revision ID: d7b5f532ddcb
Revises: 18f2e6bb0c50
Create Date: 2024-11-26 23:01:25.499331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7b5f532ddcb'
down_revision = '18f2e6bb0c50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_goal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_goal', schema=None) as batch_op:
        batch_op.drop_column('completed')

    # ### end Alembic commands ###
